# Generated by Django 6.1.1 on 2026-10-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(max_length=100)),
                ('situacion', models.CharField(max_length=200)),
                ('informacion', models.TextField()),
            ],
        ),
    ]
